# Generated by Django 5.1.6 on 2025-02-12 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_initial'),
        ('processMaster', '0002_initial'),
        ('prospect', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='prospect',
            name='psp_main001_idx',
        ),
        migrations.RenameField(
            model_name='prospect',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='prospect',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='prospect',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['prospect_number', 'first_name', 'email', 'phone', 'type', 'slug'], name='psp_main001_idx'),
        ),
    ]
