# Generated by Django 5.1.6 on 2025-02-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0003_prospect_channel_mode_prospect_mode_of_communication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='contact_method',
        ),
    ]
