# Generated by Django 5.1.6 on 2025-02-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0005_rename_intrested_in_prospect_interested_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
