# Generated by Django 5.0 on 2024-01-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process_Ladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unq_id', models.IntegerField(null=True)),
                ('approval_order', models.IntegerField(default=0)),
                ('approval_limit', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_process_ladder',
            },
        ),
        migrations.CreateModel(
            name='Process_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(blank=True, max_length=1, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('slug', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_process',
            },
        ),
    ]
