# Generated by Django 5.0 on 2024-01-07 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processMaster', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='process_master',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_master_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='process_master',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_master_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='process_ladder',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processMaster.process_master'),
        ),
        migrations.AddIndex(
            model_name='process_master',
            index=models.Index(fields=['process_desc', 'type', 'slug'], name='process_main001_idx'),
        ),
    ]
