# Generated by Django 5.0 on 2024-01-07 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locationMaster', '0001_initial'),
        ('organisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location_master',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loc_master_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location_master',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loc_org', to='organisation.organisation'),
        ),
        migrations.AddField(
            model_name='location_master',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loc_master_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='location_master',
            index=models.Index(fields=['loc_code', 'loc_desc', 'country', 'city', 'state', 'zip_code', 'slug'], name='lm_main001_idx'),
        ),
    ]
