# Generated by Django 5.0 on 2024-01-07 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menuMaster', '0002_initial'),
        ('organisation', '0001_initial'),
        ('roleMaster', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='role_master',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rm_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role_master',
            name='menu_access',
            field=models.ManyToManyField(blank=True, to='menuMaster.menu_master'),
        ),
        migrations.AddField(
            model_name='role_master',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_org', to='organisation.organisation'),
        ),
        migrations.AddField(
            model_name='role_master',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rm_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='role_master',
            index=models.Index(fields=['role_code', 'role_desc', 'slug'], name='role_main001_idx'),
        ),
    ]
