# Generated by Django 4.2.2 on 2024-05-25 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_initial'),
        ('seriesMaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series_master',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation'),
        ),
    ]
