# Generated by Django 5.0 on 2024-01-07 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessLine', '0001_initial'),
        ('departmentMaster', '0001_initial'),
        ('locationMaster', '0001_initial'),
        ('organisation', '0001_initial'),
        ('processMaster', '0001_initial'),
        ('roleMaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Master_Audit_Trail_View',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('unq_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('process_id', models.CharField(max_length=100)),
                ('process_desc', models.CharField(max_length=100)),
                ('action_desc', models.CharField(max_length=30)),
                ('changes', models.TextField()),
                ('action_by_id', models.CharField(max_length=100)),
                ('action_by', models.CharField(max_length=30)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vw_user_master_audit_trail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('no_attemp', models.IntegerField(default=0)),
                ('otp', models.IntegerField(default=0)),
                ('is_lock', models.BooleanField(default=False)),
                ('employee_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(blank=True, max_length=20, null=True)),
                ('bl_access', models.ManyToManyField(blank=True, related_name='bl_access', to='businessLine.business_line')),
                ('business_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bl_user', to='businessLine.business_line')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_created_by', to=settings.AUTH_USER_MODEL)),
                ('dep_access', models.ManyToManyField(blank=True, related_name='dep_access', to='departmentMaster.department_master')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dep_user', to='departmentMaster.department_master')),
                ('loc_access', models.ManyToManyField(blank=True, related_name='loc_access', to='locationMaster.location_master')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loc_user', to='locationMaster.location_master')),
                ('org_access', models.ManyToManyField(blank=True, related_name='org_access', to='organisation.organisation')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_user', to='organisation.organisation')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_master_user', to='processMaster.process_master')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_reporting_manager', to=settings.AUTH_USER_MODEL)),
                ('role_access', models.ManyToManyField(blank=True, related_name='role_access', to='roleMaster.role_master')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_user_master',
                'indexes': [models.Index(fields=['username', 'email', 'full_name', 'employee_code', 'slug'], name='user_main001_idx')],
            },
        ),
    ]
