# Generated by Django 5.0 on 2024-01-07 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menuMaster', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_master',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_master_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menu_master',
            name='parent_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menuMaster.menu_master'),
        ),
        migrations.AddField(
            model_name='menu_master',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_master_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='menu_master',
            index=models.Index(fields=['menu_desc', 'is_parent', 'menu_url', 'parent_icon', 'app_folder', 'order_level', 'slug'], name='menu_main001_idx'),
        ),
    ]
