# Generated by Django 5.0 on 2024-01-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuMaster', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_master',
            name='admin_only',
            field=models.BooleanField(default=True),
        ),
    ]
