# Generated by Django 5.0 on 2024-01-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuMaster', '0003_menu_master_admin_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_master',
            name='admin_only',
            field=models.BooleanField(default=False),
        ),
    ]
