# Generated by Django 5.0 on 2024-07-09 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuMaster', '0004_alter_menu_master_admin_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='menu_master',
            name='menu_main001_idx',
        ),
        migrations.AddIndex(
            model_name='menu_master',
            index=models.Index(fields=['menu_desc', 'is_parent', 'menu_url', 'parent_icon', 'order_level', 'slug'], name='menu_main001_idx'),
        ),
    ]
