# Generated by Django 5.0 on 2024-01-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit_Trail_View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_desc', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('action_desc', models.CharField(max_length=100)),
                ('changes', models.CharField(max_length=1000)),
                ('comments', models.CharField(max_length=1000)),
                ('action_by', models.CharField(max_length=1000)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vw_audit_trail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Audit_Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unq_id', models.IntegerField(null=True)),
                ('action_desc', models.TextField(blank=True, null=True)),
                ('changes', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_audit_trail',
            },
        ),
    ]
