# Generated by Django 4.2.2 on 2024-05-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditTrail', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit_trail',
            name='record_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit_trail',
            name='table_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
