# Generated by Django 5.1.6 on 2025-02-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditTrail', '0003_audit_trail_record_no_audit_trail_table_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audit_Trail_View',
        ),
    ]
